### ISSUE TITLE
annotations not displaying

### ISSUE THREAD

**Issue by pwinckles** [minad/consult#15]
Hello, I'm very new to emacs, so it's likely I'm doing something incorrectly. That said, I tried out this package this morning using the example configuration in the readme, with the final line uncommented, and noticed that the annotations do not appear when I start up emacs and enter `M-x`. I can get them to appear if I run a command like `consult-line` and then enter `M-x`. Do I have something configured incorrectly?

Separately, I noticed that `consult-apropos` does not include key bindings like the default does. As a new user, this seems a little regrettable.

**Comment by minad** [comment]
> That said, I tried out this package this morning using the example configuration in the readme, with the final line uncommented, and noticed that the annotations do not appear when I start up emacs and enter M-x. I can get them to appear if I run a command like consult-line and then enter M-x. Do I have something configured incorrectly?

Which commit are you currently using? I just want to make sure that you are using the newest versions and the newest example configuration from the README. I changed a few things in the last hours. 

What you are writing sounds like a problem with lazy loading. I will check and come back to you.

> Separately, I noticed that consult-apropos does not include key bindings like the default does. As a new user, this seems a little regrettable.

Thank you! This is a good catch. I will add this I guess!

**Comment by minad** [comment]
@pwinckles I updated the README such that the example configuration is better. Could you please try again and tell me if it works now.

**Comment by pwinckles** [comment]
I just pulled in the most recent code. It's still not loading for me on startup (I toggle `consult-annotate-mode` to get it working), but you don't need to trouble shoot it for me. I'm sure it's something wrong with my setup.

Here's my config:

```
(use-package consult
  :straight (:host github :repo "minad/consult"
                   :files ("consult.el"))
  :demand t
  ;; Replace bindings. Lazily loaded due to use-package.
  :bind (("C-c o" . consult-outline)
         ("C-x b" . consult-buffer)
         ("C-x 4 b" . consult-buffer-other-window)
         ("C-x 5 b" . consult-buffer-other-frame)
         ("C-x r x" . consult-register)
         ("C-x r b" . consult-bookmark)
         ("M-g o" . consult-outline) ;; "M-s o" is a good alternative
         ("M-g m" . consult-mark)    ;; "M-s m" is a good alternative
         ("M-g l" . consult-line)    ;; "M-s l" is a good alternative
         ("M-s m" . consult-multi-occur)
         ("M-y" . consult-yank-pop)
         ("<help> a" . consult-apropos))

  ;; The :init configuration is always executed (Not lazy!)
  :init

  ;; Replace functions (consult-multi-occur is a drop-in replacement)
  (fset 'multi-occur #'consult-multi-occur)

  ;; Optionally enable richer annotations during completion.
  ;; Must be in the :init section of use-package such that the mode gets
  ;; enabled right away. Note that this forces loading the package.
  (consult-annotate-mode)

  ;; Configure other variables in the :config section, after lazily loading the package
  :config

  ;; Enable richer annotations for M-x.
  ;; Only keybindings are shown by default, in order to reduce noise for this very common command.
  ;; * consult-annotate-symbol: Annotate with the documentation string
  ;; * consult-annotate-command-binding (default): Annotate only with the keybinding
  ;; * consult-annotate-command-full: Annotate with the keybinding and the documentation string
  (setf (alist-get 'execute-extended-command consult-annotate-alist) #'consult-annotate-command-full)
  (setf (alist-get 'consult-apropos consult-annotate-alist) #'consult-annotate-command-full)

  ;; Enable richer annotations for other functions.
  ;; (push '(my-fancy-command . consult-annotate-symbol) consult-annotate-alist)
  )
```

Thanks for the new examples! I was able to use it to figure out how to do a full annotation of apropos.

**Comment by minad** [comment]
> (setf (alist-get 'consult-apropos consult-annotate-alist) #'consult-annotate-command-full)

You don't need this. Note that consult-annotate-command-full is not the right thing, since it only works for commands. And consult-apropos completes general symbols. I could however detect commands and implement a graceful degradation. Hmm. I am not sure. There are many possibilities of doing these annotations. Users can easily write annotations functions themselves so maybe I keep things as is. I don't want to overengineer it.

> :demand t

You already have this. Lazy loading should not be a problem then. Could you try adding `:after (selectrum)`? Maybe this helps but it should in principle work without this.

Since you are already pulling via straight, could you try patching the `define-minor-mode consult-annotate-mode` with `(message "annotate enabled %s" consult-annotate-mode)` in order to check if it is getting initialized or not. I don't see where the problem is.

**Comment by pwinckles** [comment]
@minad `:after selectrum` did the trick, thanks!

To my inexperienced eye, it seems like `consult-annotate-command-full` already behaves gracefully. That is to say, it shows the binds when they're available.

**Comment by minad** [comment]
> :after selectrum did the trick, thanks!

Ok, thank you for checking. I will either add `:after selectrum` to the config example or make sure that the order does not matter. Trying the latter first...

> To my inexperienced eye, it seems like consult-annotate-command-full already behaves gracefully. That is to say, it shows the binds when they're available.

You are right. It is accidental though :D

**Comment by minad** [comment]
@pwinckles I added a fix which should make the thing a bit less order-dependent. https://github.com/minad/consult/commit/54b5c14048969081a79a6c28f97164612092eefc. However I don't think this will resolve your issue.

**Comment by minad** [comment]
@pwinckles I made more changes which change how annotations are applied and gets rid of the load order dependency, https://github.com/minad/consult/commit/40d0af672793baaad96b7e50fccd61be4be457f7. Now it should work in principle. Do you still see the problem?

**Comment by pwinckles** [comment]
@minad I pulled the latest, removed `:after selectrum`, and restarted and does indeed load correctly. Thanks!

**Comment by minad** [comment]
Cool, thank you for reporting back!
