### ISSUE TITLE
preview doesn't work for consult-ripgrep sometimes

### ISSUE THREAD

**Issue by wbtomcat** [minad/consult#404]
Hi!
It seems live preview was partially broken for consult-ripgrep in 1ace75b.
How to reproduce:
- create file ~/tmp/test/foo.txt which contains three lines
```
one
two
three
```
- create file ~/tmp/test/t/bar.txt (note, the file is inside "t" sub-directory relative to "foo.txt") which contains three lines
```
one 1
two 2
three 3
``` 
Open file ~/tmp/test/foo.txt in Emacs (checked in version 27.1). Then run `M-x consult-ripgrep` and type `two` as search regexp. In result, two strings starting from `two` will be shown in minibuffer, but live preview will work for file foo.txt only.
Here's init.el content:
```
(require 'package)
(let ((dirs (list user-emacs-directory "elpa" emacs-version)))
  (setf package-user-dir (mapconcat 'file-name-as-directory dirs "")))
(setf package-enable-at-startup nil)
(setf package-archives '(("melpa" . "https://melpa.org/packages/")
                          ("org" . "https://orgmode.org/elpa/")
                          ("gnu-devel" . "https://elpa.gnu.org/devel/")
                          ("gnu" . "https://elpa.gnu.org/packages/")))

(package-initialize)
(unless package-archive-contents
  (package-refresh-contents))

(unless (package-installed-p 'use-package)
   (package-install 'use-package))
 (require 'use-package)

(use-package vertico
  :pin gnu-devel
  :ensure t
  :custom
  (vertico-cycle nil)
  :init
  (setf vertico-count 17)
  (vertico-mode))

(use-package consult
  :load-path "/home/user/git/consult")
```
Live preview works fine for both files in 85e0322, but it doesn't work for bar.txt since next commit 1ace75b.
Could you please check my guess?

**Comment by minad** [comment]
Yes, I am aware of this issue. This is fixed in https://github.com/minad/consult/commit/37bbcd3c8a5d2105be960024091f9d6bb371cbe0. Please check.

**Comment by wbtomcat** [comment]
Sorry, but it still doesn't work: neither in `37bbcd3` nor in `e0065ae` (the latest commit).

**Comment by minad** [comment]
Thank you! You are right. There was a typo in the regular expression, see https://github.com/minad/consult/commit/a5715af2bbe74cbf12e45c542811996c19f72e4d.

**Comment by wbtomcat** [comment]
Thank you for prompt fix. No other issues were seen by me.
